---
title: Title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  invoices:
    title: Invoices
    output: true
url: 
exclude:
- ".scss"
- README.md
- node_modules
- gruntfile.js
- package.json
- Gemfile
- docker-compose.yaml
defaults:
  -
    scope:
      path: ""
      type: "Invoices"
    values:
      pdf: true
      layout: "pdf"
