---
title: Title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: 
exclude:
- ".scss"
- README.md
- node_modules
- gruntfile.js
- package.json
